package com.wapo.flagship.features.articles2.models.deserialized.tweet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class User(
    @Json(name = "contributors_enabled")
    val contributorsEnabled: Boolean?,
    @Json(name = "created_at")
    val createdAt: String?,
    @Json(name = "default_profile")
    val defaultProfile: Boolean?,
    @Json(name = "default_profile_image")
    val defaultProfileImage: Boolean?,
    @Json(name = "description")
    val description: String?,
    @Json(name = "entities")
    val entities: EntitiesX?,
    @Json(name = "favourites_count")
    val favouritesCount: Int?,
    @Json(name = "follow_request_sent")
    val followRequestSent: Boolean?,
    @Json(name = "followers_count")
    val followersCount: Int?,
    @Json(name = "following")
    val following: Boolean?,
    @Json(name = "friends_count")
    val friendsCount: Int?,
    @Json(name = "geo_enabled")
    val geoEnabled: Boolean?,
    @Json(name = "has_extended_profile")
    val hasExtendedProfile: Boolean?,
    @Json(name = "id")
    val id: Long?,
    @Json(name = "id_str")
    val idStr: String?,
    @Json(name = "is_translation_enabled")
    val isTranslationEnabled: Boolean?,
    @Json(name = "is_translator")
    val isTranslator: Boolean?,
    @Json(name = "lang")
    val lang: Any?,
    @Json(name = "listed_count")
    val listedCount: Int?,
    @Json(name = "location")
    val location: String?,
    @Json(name = "name")
    val name: String?,
    @Json(name = "notifications")
    val notifications: Boolean?,
    @Json(name = "profile_background_color")
    val profileBackgroundColor: String?,
    @Json(name = "profile_background_image_url")
    val profileBackgroundImageUrl: String?,
    @Json(name = "profile_background_image_url_https")
    val profileBackgroundImageUrlHttps: String?,
    @Json(name = "profile_background_tile")
    val profileBackgroundTile: Boolean?,
    @Json(name = "profile_banner_url")
    val profileBannerUrl: String?,
    @Json(name = "profile_image_url")
    val profileImageUrl: String?,
    @Json(name = "profile_image_url_https")
    val profileImageUrlHttps: String?,
    @Json(name = "profile_link_color")
    val profileLinkColor: String?,
    @Json(name = "profile_sidebar_border_color")
    val profileSidebarBorderColor: String?,
    @Json(name = "profile_sidebar_fill_color")
    val profileSidebarFillColor: String?,
    @Json(name = "profile_text_color")
    val profileTextColor: String?,
    @Json(name = "profile_use_background_image")
    val profileUseBackgroundImage: Boolean?,
    @Json(name = "protected")
    val `protected`: Boolean?,
    @Json(name = "screen_name")
    val screenName: String?,
    @Json(name = "statuses_count")
    val statusesCount: Int?,
    @Json(name = "time_zone")
    val timeZone: Any?,
    @Json(name = "translator_type")
    val translatorType: String?,
    @Json(name = "url")
    val url: String?,
    @Json(name = "utc_offset")
    val utcOffset: Any?,
    @Json(name = "verified")
    val verified: Boolean?,
)
