package com.washingtonpost.android.recirculation.carousel.models

class CarouselSevenLiveViewItem(
    headline: String,
    artUrl: String?,
    artAspectRatio: Float?,
    duration: Long?,
    articleUrl: String,
    mediaUrl: String?,
    pageName: String?,
    kickerName: String?,
    byLine: String,
    articleLinkIsWebType: Boolean,
    prefix: String,
    liveImage: Boolean?,
    shouldCardify: Boolean?,
    itemsRefreshInterval: Long?,
    kickerStyle: StyleEntity?,
    secondaryText: String?,
    val relativeTime: String?,
    val isRecent: Boolean = false
) : CarouselExternalViewItem(
    headline = headline,
    artUrl = artUrl,
    artAspectRatio = artAspectRatio,
    duration = duration,
    articleUrl = articleUrl,
    mediaUrl = mediaUrl,
    pageName = pageName,
    kickerName = kickerName,
    byLine = byLine,
    articleLinkIsWebType = articleLinkIsWebType,
    prefix = prefix,
    liveImage = liveImage,
    shouldCardify = shouldCardify,
    itemsRefreshInterval = itemsRefreshInterval,
    kickerStyle = kickerStyle,
    secondaryText = secondaryText,
)