[versions]
## SDK Versions
minSdk = "21"
targetSdk = "37"
compileSdk = "37"

## Library Versions
android-gradle-plugin = "9.1.1"
dateTime = "0.6.0"
kotlin = "2.3.20"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"
kmmBridge = "1.2.1"
koin = "4.1.1"
koin-annotations = "2.3.1"
ksp = "2.3.6"
ktor = "3.3.3"
multiplatform-settings = "1.3.0"
skie = "0.10.11"
stately = "2.1.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmmbridge = { id = "co.touchlab.kmmbridge", version.ref = "kmmBridge" }
kmmbridge-github = { id = "co.touchlab.kmmbridge.github", version.ref = "kmmBridge" }
kmmbridge-spm = { id = "co.touchlab.kmmbridge.spm", version.ref = "kmmBridge" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }

[libraries]

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" } #can be replaced with Kotlin-concurrency after Kotlin 2.1
stately-collections = { module = "co.touchlab:stately-concurrent-collections", version.ref = "stately" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-view-model = { module = "io.insert-koin:koin-core-viewmodel", version.ref = "koin" }
