/* Copyright (c) 2022 The Washington Post. All rights reserved. */

package com.wapo.android.commons.constants

const val COOKIE = "cookie"
const val CLIENT_ID = "clientId"
const val CLIENT_IP = "Client-IP"
const val CLIENT_USER_AGENT = "Client-UserAgent"
const val REQUEST_ID = "Request-ID"
const val CLIENT_APP = "Client-App"
const val CLIENT_APP_VERSION = "Client-App-Version"
const val DEVICE_NAME = "Device-Name"
const val OS_VERSION = "OS-Version"
const val DEVICE_ID = "deviceId"
const val AUTHORIZATION = "authorization"
const val ACCEPT = "Accept"
const val X_APP_NAME = "x-app-name"
const val X_SURFACE_NAME = "x-surface-name"
const val USER_AGENT = "User-Agent"
const val CACHE_CONTROL = "Cache-Control"
const val ARCHIVE = "archive"
const val INSTALL_ID = "installId"
const val LOGIN_ID = "wapo_login_id"
const val SECURE_LOGIN_ID = "wapo_secure_login_id"
const val CONTENT_TYPE = "Content-Type"
const val IF_MODIFIED_SINCE = "If-Modified-Since"
const val LAST_MODIFIED = "Last-Modified"
const val COUNTRY = "wp-country"
const val PLATFORM = "Platform-Name"
const val SUBSCRIPTION_ID = "wp-device-subscription"
const val SURFACE = "surface"
const val X_ACCESS_TOKEN = "x-access-token"
const val SENDER = "sender"