package com.wapo.flagship.util

import org.mockito.ArgumentMatchers
import org.mockito.kotlin.anyValueClass
import org.mockito.kotlin.internal.createInstance
import kotlin.reflect.KClass

object MatcherUtils {
    inline fun <reified T : Any> any(): T {
        if(T::class.isValue)
            return anyValueClass()

        return ArgumentMatchers.any(T::class.java) ?: createInstance()
    }

    inline fun <reified T : Any> anyOrNull(): T {
        return ArgumentMatchers.any<T>() ?: createInstance()
    }

    inline fun <reified T > anyValueClass(): T {
        require(T::class.isValue) {
            "${T::class.qualifiedName} is not a value class."
        }

        val boxImpls = T::class.java.declaredMethods.filter { it.name == "box-impl" && it.parameterCount == 1 }
        require(boxImpls.size == 1) // Sanity check

        val boxImpl = boxImpls.first()
        val boxedType = boxImpl.parameters[0].type

        return boxImpl.invoke(null, ArgumentMatchers.any(boxedType)) as T
    }

    inline fun <reified T : Any> createInstance(): T {
        return when (T::class) {
            Boolean::class -> false as T
            Byte::class -> 0.toByte() as T
            Char::class -> 0.toChar() as T
            Short::class -> 0.toShort() as T
            Int::class -> 0 as T
            Long::class -> 0L as T
            Float::class -> 0f as T
            Double::class -> 0.0 as T
            else -> createInstance(T::class)
        }
    }

    fun <T : Any> createInstance(@Suppress("UNUSED_PARAMETER") kClass: KClass<T>): T {
        return castNull()
    }

    /**
     * Uses a quirk in the bytecode generated by Kotlin
     * to cast [null] to a non-null type.
     *
     * See https://youtrack.jetbrains.com/issue/KT-8135.
     */
    @Suppress("UNCHECKED_CAST")
    private fun <T> castNull(): T = null as T
}